//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJMatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DJ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DJ()
        {
            this.Playlists = new HashSet<Playlist>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ExperienceYears { get; set; }
        public Nullable<int> PriceMin { get; set; }
        public Nullable<int> PriceMax { get; set; }
        public string Genres { get; set; }
        public string Address { get; set; }
        public string PhoneNum { get; set; }
        public string WebSite { get; set; }
        public string FacebookPage { get; set; }
        public string IGProfile { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public byte[] Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Playlist> Playlists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
