//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJMatch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DJ_MatchEntities : DbContext
    {
        public DJ_MatchEntities()
            : base("name=DJ_MatchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<DJ> DJs { get; set; }
        public virtual DbSet<Playlist> Playlists { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Song> Songs { get; set; }
        public virtual DbSet<SongsToPlaylist> SongsToPlaylists { get; set; }
        public virtual DbSet<UserAnswer> UserAnswers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
