//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJMatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ID { get; set; }
        public int DJ_ID { get; set; }
        public int UserID { get; set; }
        public string Text { get; set; }
        public int Score { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual DJ DJ { get; set; }
        public virtual User User { get; set; }
    }
}
